ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "promotionEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "promotionMinPhotos" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "promotionDiscountBps" INTEGER NOT NULL DEFAULT 0;
